version: '3.8'
services:
  arch-btw-web:
    image: nginx:latest
    container_name: arch-btw-web
    ports:
      - "5000:80"
    volumes:
      - ./arch-btw.html:/usr/share/nginx/html/index.html:ro
    restart: unless-stopped
    network_mode: bridge